### ISSUE TITLE
error: package directory 'AIOSomecomfort' does not exist

### ISSUE THREAD

**Issue by dotlambda** [mkmer/AIOSomecomfort#1]
When installing from GitHub I get
```
error: package directory 'AIOSomecomfort' does not exist
```
because the directory is called `aiosomecomfort` instead. Please fix the spelling.
Anyway, I wonder what source the sdist on PyPI was generated from because there it is called `AIOSomecomfort`.

**Comment by mkmer** [comment]
Strange, uploading everything to PyPi from here.  Should be fixed now.
