### ISSUE TITLE
aux_heat attribute doesn't update until integration reload

### ISSUE THREAD

**Issue by alvinchen1** [mkmer/AIOSomecomfort#3]
First off, thank you for much for the recent changes in 2023.2.0 on with this new code.  The Honeywell integration has been one of the most problematic/frustrating for me in the past and I really appreciate the recent code changes,  I do have one recent new issue, not sure if it is something others on HA are having, so I wanted to raise it here.

I control aux_heat using an automation that call service climate.set_aux_heat, {"aux_heat":"on"} or {"aux_heat":"off"}.  It appears to work,

<img width="692" alt="image" src="https://user-images.githubusercontent.com/26409535/216816040-66c1e5dc-0402-4ac4-a484-abab657ff9d8.png">

But, what is odd is, it doesn't seem to reflect back in the state attribute aux_heat 

<img width="324" alt="image" src="https://user-images.githubusercontent.com/26409535/216816072-1dfbd85b-a1e0-49a8-b9a4-92dd3aee677f.png">

And therefore doesn't change in the UI.

<img width="430" alt="image" src="https://user-images.githubusercontent.com/26409535/216816107-5667d396-1ef7-4018-a739-b2c6b14f878b.png">
    
So it's super cold today, and so my automations to set aux_heat on ran, once it warms up, I can try to set aux_heat to on via the gui and test, which I can't do right now since the gui thinks aux_heat is off anyway.

I have tried to tell Home Assistant to update the climate entity, thinking it may just be a refresh issue, but it's been a good half hour, and it hasn't update the entity yet.  Finally, after an hour, I reloaded the integration, and aux_heat updated.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/26409535/216816514-b9d297ae-7942-4427-a99d-355afd4a85fe.png">

<img width="425" alt="image" src="https://user-images.githubusercontent.com/26409535/216816529-b6a9bc2b-591e-40be-8eba-2c19fdf8860f.png">

Seems like aux_heat/emheat doesn't update correctly?

**Comment by mkmer** [comment]
I probably broke it :) 
It used to work (right?). Need to know for sure to know where to start looking. 

It may take a bit to figure it out. Since my system doesn't have aux heat, I'll need you to test.

 I'll keep you updated here.

**Comment by alvinchen1** [comment]
Hey, you fixed more than you broke, so that's cool. I believe it worked reliably before (one of the few things in the Honeywell Integration seemed to work before!), and since reloading the integration seems to fix it as well, there might be a clue there.  

I will say that I am running HAOS so I've got all the docker stuffz and haven't quite figured out how to inject test code into it, but I am learning and trying to figure that stuff out.  But totally understand that it's hard to troubleshoot when you can't test the code against an actually device with aux_heat.

Also, I do run HACS, so I could also disable my production Honeywell, install a custom_component of honeywell with updated AIOSomecomfort and test that way, I guess.

**Comment by mkmer** [comment]
It looks like the integration only initializes the `is_aux_heat` variable at startup.  Not sure how this could have worked before... I'll see if I can get something in for the next HA update in 2023.2.x

**Comment by alvinchen1** [comment]
Odd.  But that jives with what I'm seeing.  Thanks and great work.

**Comment by alvinchen1** [comment]
Thanks, I see the new PR.

https://github.com/home-assistant/core/pull/87465

**Comment by alvinchen1** [comment]
Shoot, it didn't get swept into 2023.2.3... maybe 2023.2.4?

**Comment by alvinchen1** [comment]
Thanks for the continued work on this integration!
