### ISSUE TITLE
302 found ...?

### ISSUE THREAD

**Issue by glyndon** [mkmer/AIOSomecomfort#6]
In case it is useful:  I've been running with 0.0.25 since you released it, and now this is the predominant error logged, about 2-8 times/daily.
```
2024-02-01 16:16:19.303 ERROR (MainThread) [somecomfort] Service Unavailable 200, (<ClientResponse(https://www.mytotalconnectcomfort.com/portal/Device/CheckDataSession/8743828) [302 Found]>
<CIMultiDictProxy('Cache-Control': 'private, s-maxage=0', 'Content-Type': 'text/html; charset=utf-8', 'Location': '/portal/Error?aspxerrorpath=/portal/Device/CheckDataSession/8743828', 'Server': 'Microsoft-IIS/8.5', 'ADRUM_0': '<obfuscated>', 'ADRUM_1': 'n:honeywell-prod_f7be1c76-506d-4111-81c5-fc62766aedb7', 'ADRUM_2': 'i:197974', 'ADRUM_3': 'e:116', 'X-Frame-Options': 'DENY', 'X-XSS-Protection': '1; mode=block', 'X-UA-Compatible': 'IE=edge', 'Date': 'Thu, 01 Feb 2024 21:16:18 GMT', 'Content-Length': '184', 'Set-Cookie': '<obfuscated>;expires=Thu, 01-Feb-2024 21:18:19 GMT;path=/;secure;httponly')>
,).
```
Didn't know how to submit this other than as a new issue, since there are none open ATM. Please close it if this detail is unneeded.

**Comment by mkmer** [comment]
This has been going on for quite a long time - the site was giving us a 200 status but not JSON via a redirect.  I recently added this debug message to catch the message for clarity.
Prior to 0.0.25 we were getting various uncaught not JSON errors.
As you can see - the site is saying "Service Unavailable".
